<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>AutoClicker</RootNamespace>
    <AssemblyName>AutoClicker</AssemblyName>
    <Version>1.5.0</Version>
    <AssemblyVersion>1.5.0.0</AssemblyVersion>
    <FileVersion>1.5.0.0</FileVersion>
    <InformationalVersion>1.5.0</InformationalVersion>
    <Product>Auto Clicker &amp; Keyboard</Product>
    <Title>Auto Clicker &amp; Keyboard</Title>
    <Description>Modern Auto Tool for Keyboard and Mouse Automation</Description>
  </PropertyGroup>

</Project>
